- name: Sync helloworld commit's to helloworld1 repo
  uses: dabreadman/sync-upstream-repo@v1.3.0

   push:
     branches: [ master ]

  jobs:
     sync:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       with:
        token: ${{ secrets.TOKEN }}
          git clone https://github.com/martinhodtembo/helloworld21.git
          cp .* temp 
          cd temp
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/victorucan/helloworld1.git
          git add .
          git commit -m "Synchronize from private repository - Triggered by Github Workflows"
          git push
          cd ..
          rm -rf temp
