name: Sync helloworld commit's to helloworld1 repo

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
    - name: Check if Commit Message Contains '[hello]'
      run : |
          echo "[LOG] It contains [HackerRank], will update to other repo"
          echo "[LOG] Cloning HackerRank-Solutions"
          git clone https://github.com/martinhodtembo/helloworld21.git
          echo "[LOG] Copying all cpp files"
          cp .* temp 
          cd temp
          echo "[LOG] Setup global config"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          echo "[LOG] Git set-url remote repository"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/victorucan/helloworld1.git
          echo "[LOG] Git add ."
          git add .
          echo "[Log] Git Commit"
          git commit -m "Synchronize from private repository - Triggered by Github Workflows"
          echo "[LOG] Git push"
          git push
          echo "[LOG] Remove Folder"
          cd ..
          rm -rf temp
